//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookIssue
    {
        public int BookIssueId { get; set; }
        public Nullable<int> BookRequestId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> LibrarianId { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public Nullable<System.DateTime> DateOfReturn { get; set; }
        public Nullable<int> DuePayment { get; set; }
    }
}
