//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Librarian
    {
        public int LibrarianId { get; set; }
        public string UserName { get; set; }
        public string LibrarianName { get; set; }
        public string LibrarianPassword { get; set; }
        public byte[] LibrarianImage { get; set; }
        public Nullable<long> LibrarianContact { get; set; }
        public string LibrarianEmail { get; set; }
    }
}
