//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public string UserName { get; set; }
        public string StudentName { get; set; }
        public string StudentPassword { get; set; }
        public byte[] StudentImage { get; set; }
        public Nullable<long> StudentContact { get; set; }
        public string StudentEmail { get; set; }
    }
}
